DATABASE_NAME = "nytaxi"
DATABASE_CONN_INF_FILEPATH = "db_conn.ini"

DATABASE_SCHEMA_SCRIPT="nytaxi_schema.sql"
DATABASE_CONSTRAINT_SCRIPT="nytaxi_fk_constraint.sql"

TRIP_TABLE_NAME = "Trip"
TAXI_TRIP_TABLE_NAME = "Taxi_Trip"
VENDOR_TABLE_NAME = "Vendor"
TAXI_TABLE_NAME = "Taxi"
PAYMENT_TABLE_NAME = "Payment"
PAYMENT_TYPE_TABLE_NAME = "Type"
PAYMENT_RATE_TABLE_NAME = "Rate"

MONTH1_DATA_FILEPATH = "yellow_tripdata_2015-01.csv"
MONTH2_DATA_FILEPATH = "yellow_tripdata_2016-01.csv"
MONTH3_DATA_FILEPATH = "yellow_tripdata_2016-02.csv"
MONTH4_DATA_FILEPATH = "yellow_tripdata_2016-03.csv"

DATA_FILEPATH_LIST = [MONTH1_DATA_FILEPATH, MONTH2_DATA_FILEPATH, MONTH3_DATA_FILEPATH, MONTH4_DATA_FILEPATH]
